framework:

    lock: '%env(LOCK_DSN)%'

    rate_limiter:
        login:
            policy: 'fixed_window'
            limit: 5
            interval: '60 minutes'
        email:
            policy: 'fixed_window'
            limit: 1
            interval: '60 minutes'
