twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'layout/_form.html.twig'
    globals:
        frontBaseUrl: '%env(string:FRONT_BASE_URL)%'

when@test:
    twig:
        strict_variables: true
