services:

  php:
    image: krav_maga_php
    build: docker/php
    volumes:
      - .:/www

  nginx:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/krav-maga.conf:/etc/nginx/conf.d/krav-maga.conf:ro
      - ./public:/www/public
    environment:
      NGINX_HOST: local.krav-maga

  db:
    image: mariadb:10.8.2
    environment:
      MARIADB_ROOT_PASSWORD: root

  node:
    image: node:16-alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
